![](https://www.dii.uchile.cl/wp-content/uploads/2021/06/Magi%CC%81ster-en-Ciencia-de-Datos.png)

# Proyecto: Innovación Tecnológica en Bodoque Bank

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### Cuerpo Docente:

- Profesor: Pablo Badilla, Ignacio Meza De La Jara
- Auxiliar: Sebastián Tinoco
- Ayudante: Diego Cortez M., Felipe Arias T.

*Por favor, lean detalladamente las instrucciones de la tarea antes de empezar a escribir.*


----

## Reglas

- Fecha de entrega: 01/06/2021
- **Grupos de 2 personas.**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Estrictamente prohibida la copia. 
- Pueden usar cualquier material del curso que estimen conveniente.

# Motivación

![](https://www.geekmi.news/__export/1621969098810/sites/debate/img/2021/05/25/juan-carlos-bodoque-1.jpg_554688468.jpg)

Juan Carlos Bodoque, el famoso periodista y empresario, decidió diversificar su portafolio de negocios y crear su propio banco. Después de varios años de investigar y analizar el mercado financiero, finalmente logró fundar su entidad bancaria con el objetivo de ofrecer a sus clientes una experiencia personalizada y confiable en sus transacciones financieras. 

Sin embargo, con las nuevas tecnologías, aparecen nuevos desafíos para la joven entidad bancaria. Por ello, Bodoque decide invertir en un equipo de expertos en tecnología y finanzas, para que Bodoque Bank implemente las últimas innovaciones en seguridad y servicio al cliente para garantizar la satisfacción y fidelización de sus clientes.

El primer objetivo de la entidad bancaria será la detección de potenciales clientes fraudulentos, para ello Bodoque Bank les hace entrega de un extenso dataset en el que se registran las actividades que han realizado sus clientes durante los últimos meses. Uno de los puntos que resaltan al pasar el conjunto de datos es que el nombre de los usuarios está protegido y que consideren cada una de las filas como una muestra independiente de la otra.

Tras la solicitud, uno de los mayores accionistas del banco llamado Mario Hugo, les sugiere que al momento de realizar el proyecto tomen las siguientes consideraciones:

- Realicen un análisis exhaustivo de cada variable, ya que los directores tienden a ser quisquillosos con puntos o definiciones sin algún fundamento claro.
- Deben ser muy claros de cómo encontrar los outliers y si es posible expliquen cómo están determinando que un cliente es fraudulento.
- Es muy probable que existan clientes con diferentes comportamientos bancarios, por lo que sería muy buena decisión de separar a los clientes en grupos etarios.


### Definición Formal del Problema

El dataset con el que se trabajará en este primer proyecto será [_The Bank Account Fraud (BAF)_](https://www.kaggle.com/datasets/sgpjesus/bank-account-fraud-dataset-neurips-2022). Este consiste en un dataset para evaluar métodos de detección de fraudes bancarios, el cuál según sus autores es:

- Realista: Se basa en un actualizado dataset de casos reales de detección de fraude bancario.
- Sesgado: Poseen distintos tipos de bias.
- Desbalanceado: Clase positiva extremadamente pequeña.
- Dinámico: Presenta datos temporales y cambios de distribución.
- Preserva la privacidad: Protege a los potenciales clientes a través de la aplicación de privacidad diferencial.

El proyecto tiene por objetivo evaluar los conocimientos adquiridos en la primera mitad del curso, consistente en manejo de datos tabulares (I/O, manipulación, agregaciones, merge y visualizaciones) más la primera parte de modelos consistente en preprocesamiento de datos y detección de anomalías. Por ende, el proyecto consiste en dos tareas principales:

1. Generar un Análisis exploratorio de Datos (EDA) que describa completamente el dataset.
2. Buscar anomalías de forma automatizada.

**Importante:** Esta permitido el uso de librerías externas a las vistas en clases para profundizar aún mas en los análisis. Sin embargo, al momento de utilizar cualqueir metodo deberán explicar que hace y el porque de su aplicación.


---

## Secciones requeridas en la entrega

La siguiente lista detalla las secciones que debe contener su notebook para resolver el proyecto. Es importante que al momento de desarrollar cada una de las secciones, estas sean escritas en un formato tipo **informe**, donde describan detalladamente cada uno de los puntos realizados.

### 1. Introducción [0.5 Puntos]

Elaborar una breve introducción con todo lo necesario para entender qué realizarán durante su proyecto. La idea es que describan de manera formal el proyecto con sus propias palabras y logren describir algunos aspectos básicos tanto del dataset como del análisis a realizar sobre los datos.

Por lo anterior, en esta sección ustedes deberán ser capaces de:

- Describir la tarea asociada al dataset.
- Describir brevemente los datos de entrada que les provee el problema.
- Plantear hipótesis de cómo podrían abordar el problema.

### 2. Lectura y Manejo de Datos [1 Punto]

Este punto tiene por objetivo evaluar la capacidad de leer y manejar distintas fuentes de datos y unirlas.
Para esto, se les provee de 3 datasets distintos: 

- `df_1.parquet` que contiene una cierta cantidad de ejemplos.
- `df_2.parquet` que contiene el resto de los ejemplos.
- `df_email_phone.parquet` que contiene características exclusivas relacionadas a los emails y teléfonos de los ejemplos.

Tanto `df_1` como `df_2` son dataframes que contienen conjuntos (no necesariamente disjuntos) de ejemplos obtenidos a partir de distintas fuentes (la primera más confiable que la segunda)  mientras que `df_email_phone` contiene nuevas características que deben ser fusionadas con el conjunto de ejemplos.
Dicho esto, para este punto se le solicita:

1. Cargar los datasets usando pandas.
2. Explorar superficialmente los datsets por medio de `.head(5)` e `.info()` y reportar número de filas y columnas de cada dataset.
3. Unir los datasets con los conjuntos de ejemplos en un único dataset.
4. Combinar el datasets con ejemplos con las nuevas características usando la estrategia `outer`.
5. Explorar nulos y duplicados de datos (i.e., generar conteos de cada uno y ver algunos de sus ejemplos), explicar su origen y entregar una solución sencilla a estos casos.
6. Limpiar datos y reportar modificaciones a los datasets originales (cuántos ejemplos se eliminaron, cuántos ejemplos quedaron finalmente, etc...).
7. Realizar una segmentación etaria de los datos creando una columna llamada `segmentacion_etaria` para clasificar a los diferentes usuarios. Para la segmentación utilice los siguientes rangos:
   - Joven (Menor a 18 años)
   - Adulto-Joven (18 - 26 años)
   - Adulto (27- 59 años)
   - Persona Mayor (60 años o mas).


### 3. Análisis Exploratorio de Datos [1 Punto]

Esta sección se busca evaluar la capacidad de generar reportes y conclusiones a partir de los patrones observados en estos.

- Utilizando `pandas-profiling` (nombre de la librería: `ydata-profiling`), explore:

    * Analizar cantidad de datos nulos, tipos de datos, duplicados, distribuciones de las variables a través de histogramas.
    * Generar visualizaciones de las interacciones (como por ejemplo, una scatter matrix) en las distintas variables.
    * Ver las correlaciones entre las distintas variables y los valores faltantes de cada una de estas. 
    * Reportar los patrones interesantes observados. Ejemplos:
        - Se observó que las variables numéricas A, B y C siguen una distribución normal / exponencial / logarítmica / no presenta distribución conocida debido a que (usar información sobre el descripción de cada variable)....
        - La mayoría de los ejemplos de las variables I, J y K tienen valor 0.
        - La variable M presenta gran cantidad de outliers.
        - Se observó que las variables categóricas E y F están bien balanceadas / presentan un gran desbalance.
        - Del gráfico de correlaciones se puede inferir que X, Y y Z tienen una correlación alta/baja entre ellas.



### 4. Preparación de Datos [1 Punto]

*Esta sección consiste en generar los distintos pasos para preparar sus datos con el fin de luego poder crear su modelo.*

Dentro de los aspectos minimos que se les solicitarán en este desarrollo estan:

- Definir preprocesadores para datos categóricos y ordinales.
- Setear las transformaciones en un `ColumnTransformer`.
- Transformar todo el datset.

**Notas**: 

- Las variables `id` y `fraud_bool` no deben ser transformadas, pero si pasadas a la siguiente etapa. (Estudiar la transformación `passthrough`).
- La salida de la transformación debe ser un pandas dataframe. Para esto, investiguen acerca de la nueva [`set_output` API](https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html). Si se levanta un error por matriz sparse, desactiven su uso en la transformación correspondiente.

### 5. Visualización en baja dimensionalidad [1 Punto]

Programar un script para proyectar los datos en baja dimensionalidad usando `PCA` o `UMAP`.

**Notas**: 

- Para realizar las proyecciones no consideren la variable `fraud_bool`, ya que esto provocaría un _data leakage_ (i.e., usar información del futuro para analizar el mismo fenómeno que quieren descubrir).
- Utilice un muestreo significativo del dataframe (10k a 25k ejemplos) para generar las proyecciones. De lo contrario, probablemente el proyector no sea capaz de asignar todos los recursos necesarios y lance alguna excepción.

Luego, por cada segmento etario generado en la sección 2, implemente un gráfico de dispersión (idealmente en plotly express) la proyección en 2D generada y coloree cada punto según la etiqueta `fraud_bool`.

Reportar si existen patrones y/o relaciones interesantes con respecto a variables de interés.


### 6. Explorar Anomalías [1.5 Puntos]

Proponer una técnica para detectar clientes fraudulentos en base a detección de anomalías. 
Al igual que el punto anterior, la técnica que proponga debe ser aplicada por separado en los diferentes segmentos etarios descritos en el punto 2 (es decir, debe entrenar un detector de anomalías para cada uno de estos grupos). 

Luego, al igual que el punto anterior, genere un gráfico de dispersión con las proyecciones 2D en donde el coloreado sea ahora las etiquetas predichas por el detector de anomalías.

Por último, usando queries de numpy/pandas, calcule dos ratios (P y R):

- P: Cantidad de ejemplos predichos correctamente como fraude / cantidad total de datos predichos como fraude.
- R: Cantidad de ejemplos predichos correctamente como fraude / cantidad total de ejemplos que eran realmente fraude.


De los resultados obtenidos responda las siguientes preguntas:

- ¿Qué significan los ratios y sus valores?
- ¿Qué tan correctas fueron las predicciones realizadas por su modelo según los ratios calculados?
- ¿Son coherentes los resultados obtenidos?.
- ¿Cómo se comportan los casos de fraudes para los diferentes rangos etarios?

Justifique cada una de sus respuestas.

---

## Esquema de la Tarea


Pueden usar el siguiente esquema para organizar la tarea (y borrar todo lo anterior).
Obviamente **no deben limitarse a lo que está escrito en esta**: puede incrementar en caso de más técnicas y obviar algunas partes en caso que alguna y otro punto no aplique a su problema.

Pueden borrar las instrucciones anteriores y quedarse solo con lo que viene a continuación.

---
<br>

<br>

<br>



# Proyecto

### Equipo:

- Sebastián Versluys
- Josué Guillen


### Link de repositorio de GitHub: `https://github.com/Nietsabas/MDS7202`




## 1. Introducción


In [ ]:
...

## 2. Lectura y Manejo de Datos




### 2.1 Cargar datos en dataframes

In [ ]:
import pandas as pd
#Instalando librerias necesarias para leer archivos en formato .parquet
!pip install pyarrow
!pip install fastparquet

# Cargar df_1.parquet
df_1 = pd.read_parquet('df_1.parquet')

# Cargar df_2.parquet
df_2 = pd.read_parquet('df_2.parquet')

# Cargar df_email_phone.parquet
df_email_phone = pd.read_parquet('df_email_phone.parquet')


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### 2.2 Exploración inicial

In [ ]:
# Exploración df_1.parquet
print("===================================== df_1.parquet =========================================")
print("Número de filas y columnas:", df_1.shape)
print("Información del dataset:")
df_1.info()
print()
print("Primeras 5 filas:")
df_1.head(5)



===================================== df_1.parquet =========================================
Número de filas y columnas: (389782, 29)
Información del dataset:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 389782 entries, 104446 to 193209
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   id                            389782 non-null  int64  
 1   fraud_bool                    389782 non-null  int64  
 2   income                        389782 non-null  float64
 3   prev_address_months_count     389782 non-null  int64  
 4   current_address_months_count  389782 non-null  int64  
 5   customer_age                  389782 non-null  int64  
 6   days_since_request            389782 non-null  float64
 7   intended_balcon_amount        389782 non-null  float64
 8   payment_type                  389782 non-null  object 
 9   zip_count_4w                  389782 non-null  int64  
 10  

id  fraud_bool  income  prev_address_months_count  \
104446  729517           0     0.7                         -1   
269483  149585           0     0.8                         -1   
4102     64486           0     0.9                         -1   
351767  825283           0     0.5                         -1   
126377    8308           0     0.9                         -1   

        current_address_months_count  customer_age  days_since_request  \
104446                           305            60            0.030059   
269483                           140            50            0.015659   
4102                             171            50            0.001409   
351767                            85            30            0.027292   
126377                            39            30            0.010945   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
104446               -1.599455           AC           990  ...   
269483                3.951994           AA          1269  ...   
4102                 28.159779           AB          4430  ...   
351767               -1.310498           AB          1698  ...   
126377               -1.450972           AC           569  ...   

        proposed_credit_limit  foreign_request    source  \
104446                  500.0                0  INTERNET   
269483                  200.0                0  INTERNET   
4102                   1500.0                0  INTERNET   
351767                  200.0                0  INTERNET   
126377                  200.0                0  INTERNET   

        session_length_in_minutes device_os  keep_alive_session  \
104446                   8.865992   windows                   0   
269483                   4.654872     linux                   1   
4102                     3.720953     linux                   1   
351767                   2.912670   windows                   1   
126377                   2.283680     other                   1   

       device_fraud_count  month        x1        x2  
104446                  0      2 -0.245425  0.568811  
269483                  0      7  0.009336 -2.096682  
4102                    0      1  2.229616 -0.005823  
351767                  0      3 -0.193945  0.861207  
126377                  0      3 -2.440650  0.354986  

[5 rows x 29 columns]

In [ ]:
# Exploración df_2.parquet
print("===================================== df_2.parquet =========================================")
print("Número de filas y columnas:", df_2.shape)
print("Información del dataset:")
df_2.info()
print()
print("Primeras 5 filas:")
df_2.head(5)

===================================== df_2.parquet =========================================
Número de filas y columnas: (747410, 29)
Información del dataset:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 747410 entries, 699954 to 384611
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   id                            747410 non-null  int64  
 1   fraud_bool                    747410 non-null  int64  
 2   income                        747410 non-null  float64
 3   prev_address_months_count     747410 non-null  int64  
 4   current_address_months_count  747410 non-null  int64  
 5   customer_age                  747410 non-null  int64  
 6   days_since_request            747410 non-null  float64
 7   intended_balcon_amount        747410 non-null  float64
 8   payment_type                  747410 non-null  object 
 9   zip_count_4w                  747410 non-null  int64  
 10  

id  fraud_bool  income  prev_address_months_count  \
699954  303612           0     0.8                         -1   
701206  568066           0     0.9                         -1   
270304  893344           0     0.7                         -1   
346538  247688           0     0.8                         -1   
147297  674478           0     0.8                         -1   

        current_address_months_count  customer_age  days_since_request  \
699954                            21            40            0.010837   
701206                            70            50            0.711485   
270304                           133            50            0.006856   
346538                           207            50            0.026194   
147297                            24            50            0.012646   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
699954               -0.853976           AD           239  ...   
701206               25.137456           AA          1873  ...   
270304               -0.815330           AC           675  ...   
346538               -0.736615           AB           999  ...   
147297               10.744253           AA          3198  ...   

        proposed_credit_limit  foreign_request    source  \
699954                  200.0                0  INTERNET   
701206                  200.0                0  INTERNET   
270304                 1000.0                0  INTERNET   
346538                  200.0                0  INTERNET   
147297                  500.0                1  INTERNET   

        session_length_in_minutes device_os  keep_alive_session  \
699954                  48.127390     other                   0   
701206                   8.792273   windows                   1   
270304                  15.916225     other                   1   
346538                   0.509942     linux                   1   
147297                  10.562945     other                   0   

       device_fraud_count  month        x1        x2  
699954                  0      3  0.236931  0.077061  
701206                  0      3  0.571536  1.151563  
270304                  0      7  0.224252 -0.590459  
346538                  0      6  0.648528 -0.315911  
147297                  0      6  0.041475  0.383332  

[5 rows x 29 columns]

In [ ]:
# Exploración df_email_phone
print("===================================== df_email_phone.parquet =========================================")
print("Número de filas y columnas:", df_email_phone.shape)
print("Información del dataset:")
df_email_phone.info()
print("Primeras 5 filas:")
df_email_phone.head(5)

===================================== df_email_phone.parquet =========================================
Número de filas y columnas: (934730, 7)
Información del dataset:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 934730 entries, 987231 to 986114
Data columns (total 7 columns):
 #   Column                            Non-Null Count   Dtype  
---  ------                            --------------   -----  
 0   id                                934730 non-null  int64  
 1   name_email_similarity             934730 non-null  float64
 2   date_of_birth_distinct_emails_4w  934730 non-null  int64  
 3   email_is_free                     934730 non-null  int64  
 4   device_distinct_emails_8w         934730 non-null  int64  
 5   phone_home_valid                  934730 non-null  int64  
 6   phone_mobile_valid                934730 non-null  int64  
dtypes: float64(1), int64(6)
memory usage: 57.1 MB
Primeras 5 filas:


id  name_email_similarity  date_of_birth_distinct_emails_4w  \
987231  624588               0.555653                                15   
79954   620810               0.849718                                 2   
567130  580633               0.110898                                 3   
500891    6379               0.671250                                15   
55399   366511               0.772932                                 7   

        email_is_free  device_distinct_emails_8w  phone_home_valid  \
987231              0                          1                 0   
79954               0                          1                 0   
567130              0                          1                 1   
500891              0                          1                 0   
55399               0                          1                 0   

        phone_mobile_valid  
987231                   1  
79954                    0  
567130                   0  
500891                   1  
55399                    1

### 2.3 Unir dataframes

In [ ]:
df = pd.concat([df_1, df_2])
df.head(5)

id  fraud_bool  income  prev_address_months_count  \
104446  729517           0     0.7                         -1   
269483  149585           0     0.8                         -1   
4102     64486           0     0.9                         -1   
351767  825283           0     0.5                         -1   
126377    8308           0     0.9                         -1   

        current_address_months_count  customer_age  days_since_request  \
104446                           305            60            0.030059   
269483                           140            50            0.015659   
4102                             171            50            0.001409   
351767                            85            30            0.027292   
126377                            39            30            0.010945   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
104446               -1.599455           AC           990  ...   
269483                3.951994           AA          1269  ...   
4102                 28.159779           AB          4430  ...   
351767               -1.310498           AB          1698  ...   
126377               -1.450972           AC           569  ...   

        proposed_credit_limit  foreign_request    source  \
104446                  500.0                0  INTERNET   
269483                  200.0                0  INTERNET   
4102                   1500.0                0  INTERNET   
351767                  200.0                0  INTERNET   
126377                  200.0                0  INTERNET   

        session_length_in_minutes device_os  keep_alive_session  \
104446                   8.865992   windows                   0   
269483                   4.654872     linux                   1   
4102                     3.720953     linux                   1   
351767                   2.912670   windows                   1   
126377                   2.283680     other                   1   

       device_fraud_count  month        x1        x2  
104446                  0      2 -0.245425  0.568811  
269483                  0      7  0.009336 -2.096682  
4102                    0      1  2.229616 -0.005823  
351767                  0      3 -0.193945  0.861207  
126377                  0      3 -2.440650  0.354986  

[5 rows x 29 columns]

In [ ]:
df_nulos = df.isnull().sum()
df_nulos

id                              0
fraud_bool                      0
income                          0
prev_address_months_count       0
current_address_months_count    0
customer_age                    0
days_since_request              0
intended_balcon_amount          0
payment_type                    0
zip_count_4w                    0
velocity_6h                     0
velocity_24h                    0
velocity_4w                     0
bank_branch_count_8w            0
employment_status               0
credit_risk_score               0
housing_status                  0
bank_months_count               0
has_other_cards                 0
proposed_credit_limit           0
foreign_request                 0
source                          0
session_length_in_minutes       0
device_os                       0
keep_alive_session              0
device_fraud_count              0
month                           0
x1                              0
x2                              0
dtype: int64

### 2.4 Unir nuevas variables

In [ ]:
df = pd.merge(df, df_email_phone, on='id', how='outer')


In [ ]:
df.head(10)

id  fraud_bool  income  prev_address_months_count  \
0  729517         0.0     0.7                       -1.0   
1  729517         0.0     0.7                       -1.0   
2  149585         0.0     0.8                       -1.0   
3  149585         0.0     0.8                       -1.0   
4   64486         0.0     0.9                       -1.0   
5  825283         0.0     0.5                       -1.0   
6  825283         0.0     0.5                       -1.0   
7    8308         0.0     0.9                       -1.0   
8    8308         0.0     0.9                       -1.0   
9  891636         0.0     0.6                       -1.0   

   current_address_months_count  customer_age  days_since_request  \
0                         305.0          60.0            0.030059   
1                         305.0          60.0            0.030059   
2                         140.0          50.0            0.015659   
3                         140.0          50.0            0.015659   
4                         171.0          50.0            0.001409   
5                          85.0          30.0            0.027292   
6                          85.0          30.0            0.027292   
7                          39.0          30.0            0.010945   
8                          39.0          30.0            0.010945   
9                         137.0          60.0            0.046158   

   intended_balcon_amount payment_type  zip_count_4w  ...  device_fraud_count  \
0               -1.599455           AC         990.0  ...                 0.0   
1               -1.599455           AC         990.0  ...                 0.0   
2                3.951994           AA        1269.0  ...                 0.0   
3                3.951994           AA        1269.0  ...                 0.0   
4               28.159779           AB        4430.0  ...                 0.0   
5               -1.310498           AB        1698.0  ...                 0.0   
6               -1.310498           AB        1698.0  ...                 0.0   
7               -1.450972           AC         569.0  ...                 0.0   
8               -1.450972           AC         569.0  ...                 0.0   
9               25.841925           AA        1512.0  ...                 0.0   

   month        x1        x2 name_email_similarity  \
0    2.0 -0.245425  0.568811              0.883485   
1    2.0 -0.245425  0.568811              0.883485   
2    7.0  0.009336 -2.096682              0.113208   
3    7.0  0.009336 -2.096682              0.113208   
4    1.0  2.229616 -0.005823              0.792797   
5    3.0 -0.193945  0.861207              0.865082   
6    3.0 -0.193945  0.861207              0.865082   
7    3.0 -2.440650  0.354986              0.450024   
8    3.0 -2.440650  0.354986              0.450024   
9    2.0  2.192960  0.484068              0.383238   

   date_of_birth_distinct_emails_4w email_is_free  device_distinct_emails_8w  \
0                               2.0           1.0                        1.0   
1                               2.0           1.0                        1.0   
2                               4.0           1.0                        1.0   
3                               4.0           1.0                        1.0   
4                               4.0           0.0                        1.0   
5                              10.0           0.0                        1.0   
6                              10.0           0.0                        1.0   
7                              13.0           1.0                        1.0   
8                              13.0           1.0                        1.0   
9                               2.0           1.0                        1.0   

   phone_home_valid  phone_mobile_valid  
0               0.0                 1.0  
1               0.0                 1.0  
2               1.0                 1.0  
3               1.0                 1.0  
4       

In [ ]:
df.shape

(1198151, 35)

### 2.5 Verificar nulos y duplicados, generar explicaciones sobre sus fuentes y proponer soluciones.



In [ ]:
valores_nulos = df.isnull().sum()
print("Conteo de valores nulos por columna:")
valores_nulos


Conteo de valores nulos por columna:


id                                      0
fraud_bool                          60959
income                              60959
prev_address_months_count           60959
current_address_months_count        60959
customer_age                        60959
days_since_request                  60959
intended_balcon_amount              60959
payment_type                        60959
zip_count_4w                        60959
velocity_6h                         60959
velocity_24h                        60959
velocity_4w                         60959
bank_branch_count_8w                60959
employment_status                   60959
credit_risk_score                   60959
housing_status                      60959
bank_months_count                   60959
has_other_cards                     60959
proposed_credit_limit               60959
foreign_request                     60959
source                              60959
session_length_in_minutes           60959
device_os                         

In [ ]:
num_filas_duplicadas = df.duplicated().sum()
print("\nConteo de filas duplicados:", num_filas_duplicadas)


Conteo de filas duplicados: 202334


In [ ]:
filas_con_NA = df[df.isnull().any(axis=1)].head()
print("\nEjemplos de filas con valores nulos:")
filas_con_NA


Ejemplos de filas con valores nulos:


id  fraud_bool  income  prev_address_months_count  \
428832  893344         0.0     0.7                       -1.0   
428833  893344         0.0     0.7                       -1.0   
428834  893344         0.0     0.7                       -1.0   
428835  893344         0.0     0.7                       -1.0   
428853  762227         0.0     0.8                       -1.0   

        current_address_months_count  customer_age  days_since_request  \
428832                         133.0          50.0            0.006856   
428833                         133.0          50.0            0.006856   
428834                         133.0          50.0            0.006856   
428835                         133.0          50.0            0.006856   
428853                          78.0          40.0            0.017146   

        intended_balcon_amount payment_type  zip_count_4w  ...  \
428832               -0.815330           AC         675.0  ...   
428833               -0.815330           AC         675.0  ...   
428834               -0.815330           AC         675.0  ...   
428835               -0.815330           AC         675.0  ...   
428853               51.794412           AA         932.0  ...   

        device_fraud_count  month        x1        x2 name_email_similarity  \
428832                 0.0    7.0  0.224252 -0.590459                   NaN   
428833                 0.0    7.0  0.224252 -0.590459                   NaN   
428834                 0.0    7.0  0.224252 -0.590459                   NaN   
428835                 0.0    7.0  0.224252 -0.590459                   NaN   
428853                 0.0    2.0 -0.265474 -1.189797                   NaN   

        date_of_birth_distinct_emails_4w email_is_free  \
428832                               NaN           NaN   
428833                               NaN           NaN   
428834                               NaN           NaN   
428835                               NaN           NaN   
428853                               NaN           NaN   

        device_distinct_emails_8w  phone_home_valid  phone_mobile_valid  
428832                        NaN               NaN                 NaN  
428833                        NaN               NaN                 NaN  
428834                        NaN               NaN                 NaN  
428835                        NaN               NaN                 NaN  
428853                        NaN               NaN                 NaN  

[5 rows x 35 columns]

In [ ]:
filas_duplicadas = df[df.duplicated(keep=False)].head()
print("\nEjemplos de filas con valores duplicados:")
filas_duplicadas


Ejemplos de filas con valores duplicados:


id  fraud_bool  income  prev_address_months_count  \
0  729517         0.0     0.7                       -1.0   
1  729517         0.0     0.7                       -1.0   
2  149585         0.0     0.8                       -1.0   
3  149585         0.0     0.8                       -1.0   
5  825283         0.0     0.5                       -1.0   

   current_address_months_count  customer_age  days_since_request  \
0                         305.0          60.0            0.030059   
1                         305.0          60.0            0.030059   
2                         140.0          50.0            0.015659   
3                         140.0          50.0            0.015659   
5                          85.0          30.0            0.027292   

   intended_balcon_amount payment_type  zip_count_4w  ...  device_fraud_count  \
0               -1.599455           AC         990.0  ...                 0.0   
1               -1.599455           AC         990.0  ...                 0.0   
2                3.951994           AA        1269.0  ...                 0.0   
3                3.951994           AA        1269.0  ...                 0.0   
5               -1.310498           AB        1698.0  ...                 0.0   

   month        x1        x2 name_email_similarity  \
0    2.0 -0.245425  0.568811              0.883485   
1    2.0 -0.245425  0.568811              0.883485   
2    7.0  0.009336 -2.096682              0.113208   
3    7.0  0.009336 -2.096682              0.113208   
5    3.0 -0.193945  0.861207              0.865082   

   date_of_birth_distinct_emails_4w email_is_free  device_distinct_emails_8w  \
0                               2.0           1.0                        1.0   
1                               2.0           1.0                        1.0   
2                               4.0           1.0                        1.0   
3                               4.0           1.0                        1.0   
5                              10.0           0.0                        1.0   

   phone_home_valid  phone_mobile_valid  
0               0.0                 1.0  
1               0.0                 1.0  
2               1.0                 1.0  
3               1.0                 1.0  
5               0.0                 1.0  

[5 rows x 35 columns]

Veamos el origen de estos duplicados y NA values, para ello primero analicemos si los valores nulos o filas duplicadas provienen de los datasets originales:

In [ ]:
nulos_df_1 = df_1.isnull().sum()
nulos_df_1

id                              0
fraud_bool                      0
income                          0
prev_address_months_count       0
current_address_months_count    0
customer_age                    0
days_since_request              0
intended_balcon_amount          0
payment_type                    0
zip_count_4w                    0
velocity_6h                     0
velocity_24h                    0
velocity_4w                     0
bank_branch_count_8w            0
employment_status               0
credit_risk_score               0
housing_status                  0
bank_months_count               0
has_other_cards                 0
proposed_credit_limit           0
foreign_request                 0
source                          0
session_length_in_minutes       0
device_os                       0
keep_alive_session              0
device_fraud_count              0
month                           0
x1                              0
x2                              0
dtype: int64

In [ ]:
num_filas_duplicadas_df_1 = df_1.duplicated().sum()
print("\nConteo de filas duplicados:", num_filas_duplicadas_df_1)


Conteo de filas duplicados: 0


In [ ]:
nulos_df_2 = df_2.isnull().sum()
nulos_df_2

id                              0
fraud_bool                      0
income                          0
prev_address_months_count       0
current_address_months_count    0
customer_age                    0
days_since_request              0
intended_balcon_amount          0
payment_type                    0
zip_count_4w                    0
velocity_6h                     0
velocity_24h                    0
velocity_4w                     0
bank_branch_count_8w            0
employment_status               0
credit_risk_score               0
housing_status                  0
bank_months_count               0
has_other_cards                 0
proposed_credit_limit           0
foreign_request                 0
source                          0
session_length_in_minutes       0
device_os                       0
keep_alive_session              0
device_fraud_count              0
month                           0
x1                              0
x2                              0
dtype: int64

In [ ]:
num_filas_duplicadas_df_2 = df_2.duplicated().sum()
print("\nConteo de filas duplicados:", num_filas_duplicadas_df_2)


Conteo de filas duplicados: 163292


In [ ]:
nulos_df_email_phone = df_email_phone.isnull().sum()
nulos_df_email_phone

id                                  0
name_email_similarity               0
date_of_birth_distinct_emails_4w    0
email_is_free                       0
device_distinct_emails_8w           0
phone_home_valid                    0
phone_mobile_valid                  0
dtype: int64

In [ ]:
num_filas_duplicadas_df_email_phone = df_email_phone.duplicated().sum()
print("\nConteo de filas duplicados:", num_filas_duplicadas_df_email_phone)


Conteo de filas duplicados: 0


Después de este análisis, podemos darnos cuenta que:

- Valores nulos (NA): Se observa que varias columnas del df resultante tienen una cantidad significativa de valores nulos. Por ejemplo, las columnas "fraud_bool_x", "income_x", "prev_address_months_count_x", "current_address_months_count_x" y otras presentan un alto número de valores nulos. Podemos ver que los nulos provienen exclusivamente del proceso de merge que se hizo entre la concatenación de df_1 y df_2 con df_email_phone, ya que si se unen datasets con diferentes formatos de registro o claves primarias inconsistentes, pueden surgir valores nulos.

- Filas duplicadas: Se encontraron ejemplos de filas duplicadas en el dataset df resultante del merge que aproximadamente son 202334 filas duplicadas. Por ejemplo, la fila con el ID 729517 o 149585 se repite varias veces, lo que indica la presencia de duplicados para este ID. Esto se debe a que df_2 ya contenia duplicados aproximadamente 163292 y lo otra parte se generó durante el proceso de merge  de los datasets  df_1 y df_2 con df_email_phone.

Para abordar estos problemas, se puede hacer lo siguiente:

- Eliminación de filas con valores nulos:

Se pueden eliminar las filas que contienen valores nulos en alguna de las columnas utilizando el método dropna(), esto reduciría el dataset y evitaría posibles problemas en el análisis posterior al no haber datos incompletos y brindar consistencia al dataset, sin embargo esto también puede reducir significativamente el tamaño del dataset, lo que implica una pérdida de información potencial y falta de representatividad y generalización de los resultados posteriores al hacer algún análisis.

- Imputación de valores nulos:

Esta estrategía consiste en reemplazar los valores nulos con valores estimados o inferidos a partir de la información disponible en el dataset, esto permite aprovechar la información de las demás columnas y conservar el tamaño original del dataset, además de evitar la pérdida de datos y mantiene la representatividad de las muestras. La gran desventaja de esta imputación es que es posible intoducir sesgo en la misma, por lo que la elección de una técnica de imputación adecuada podría ser crucial.

- Eliminación de filas duplicadas:

Si las filas duplicadas no aportan información adicional o son erróneas, se pueden eliminar utilizando el método drop_duplicates(). No cabe dudas que eliminar las filas duplicadas en el dataset resultante es necesario ya que tener filas duplicadas introduce sesgos en el análisis, por lo que tratar esto asegura la unicidad de los datos.

En el siguiente punto se analizará la estrategia a utilizar con la justificación respectiva:

### 2.6 Limpiar

Veamos primero el porcentaje de duplicados del dataset df

In [ ]:
duplicados = df.duplicated()
porcentaje_duplicados = (duplicados.sum() / len(df)) * 100
print(f"Porcentaje de duplicados: {porcentaje_duplicados:.2f}%")


Porcentaje de duplicados: 16.89%


In [ ]:
df.shape

(1198151, 35)

Notemos que el porcentaje de duplicados es apenas el 16.89% de los datos, teniendo aproximadamente df shape  de (1198151, 35), por lo que podemos eliminar los duplicados, en efecto:

In [ ]:
df = df.drop_duplicates()
df.shape


(995817, 35)

Notemos que luego de la eliminación aún seguimos conservando gran cantidad de los datos pasamos de 1198151 con un 16% de valores duplicados a 995817 sin muestras duplicadas

Veamos ahora que haremos con los nulos, primero veamos el porcentaje de los valores nulos en cada columna:

In [ ]:
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100
print("Porcentaje de nulos por columna:")
porcentaje_nulos


Porcentaje de nulos por columna:


id                                  0.000000
fraud_bool                          6.121506
income                              6.121506
prev_address_months_count           6.121506
current_address_months_count        6.121506
customer_age                        6.121506
days_since_request                  6.121506
intended_balcon_amount              6.121506
payment_type                        6.121506
zip_count_4w                        6.121506
velocity_6h                         6.121506
velocity_24h                        6.121506
velocity_4w                         6.121506
bank_branch_count_8w                6.121506
employment_status                   6.121506
credit_risk_score                   6.121506
housing_status                      6.121506
bank_months_count                   6.121506
has_other_cards                     6.121506
proposed_credit_limit               6.121506
foreign_request                     6.121506
source                              6.121506
session_le

In [ ]:
df_sin_nulos = df.dropna()

porcentaje_eliminado = ((len(df) - len(df_sin_nulos)) / len(df)) * 100

print(f"Porcentaje de filas eliminadas: {porcentaje_eliminado:.2f}%")
print(f"Shape del df sin nulos:")
df_sin_nulos.shape

Porcentaje de filas eliminadas: 12.26%
Shape del df sin nulos:


(873771, 35)

Notemos que apenas los nulos para cada columna son el 6.13% y al eliminarlos el dataset se reduce en un 12,26% pasando de 995817 a  873771 por lo que podemos eliminarlos, ya que no perderemos demasiada información, en efecto:

In [ ]:
df = df_sin_nulos
df.head(5)

id  fraud_bool  income  prev_address_months_count  \
0  729517         0.0     0.7                       -1.0   
2  149585         0.0     0.8                       -1.0   
4   64486         0.0     0.9                       -1.0   
5  825283         0.0     0.5                       -1.0   
7    8308         0.0     0.9                       -1.0   

   current_address_months_count  customer_age  days_since_request  \
0                         305.0          60.0            0.030059   
2                         140.0          50.0            0.015659   
4                         171.0          50.0            0.001409   
5                          85.0          30.0            0.027292   
7                          39.0          30.0            0.010945   

   intended_balcon_amount payment_type  zip_count_4w  ...  device_fraud_count  \
0               -1.599455           AC         990.0  ...                 0.0   
2                3.951994           AA        1269.0  ...                 0.0   
4               28.159779           AB        4430.0  ...                 0.0   
5               -1.310498           AB        1698.0  ...                 0.0   
7               -1.450972           AC         569.0  ...                 0.0   

   month        x1        x2 name_email_similarity  \
0    2.0 -0.245425  0.568811              0.883485   
2    7.0  0.009336 -2.096682              0.113208   
4    1.0  2.229616 -0.005823              0.792797   
5    3.0 -0.193945  0.861207              0.865082   
7    3.0 -2.440650  0.354986              0.450024   

   date_of_birth_distinct_emails_4w email_is_free  device_distinct_emails_8w  \
0                               2.0           1.0                        1.0   
2                               4.0           1.0                        1.0   
4                               4.0           0.0                        1.0   
5                              10.0           0.0                        1.0   
7                              13.0           1.0                        1.0   

   phone_home_valid  phone_mobile_valid  
0               0.0                 1.0  
2               1.0                 1.0  
4               0.0                 1.0  
5               0.0                 1.0  
7               0.0                 0.0  

[5 rows x 35 columns]

### 2.7 Segmentación

Hagamos ahora una segmentacion etaria en base a lo que nos dice el enunciado:

In [ ]:
''' 
Usaremos la funcion cut de pandas, pues esta se utiliza
para discretizar o dividir una variable continua en intervalos o categorías específicas

Para ello definamos los rangos:

'''

rangos = [0, 18, 27, 60, float('inf')]
etiquetas = ["Joven", "Adulto-Joven", "Adulto", "Persona Mayor"]

df["segmentacion_etaria"] = pd.cut(df["customer_age"], bins=rangos, labels=etiquetas, right=False)
df.head(5)


id  fraud_bool  income  prev_address_months_count  \
0  729517         0.0     0.7                       -1.0   
2  149585         0.0     0.8                       -1.0   
4   64486         0.0     0.9                       -1.0   
5  825283         0.0     0.5                       -1.0   
7    8308         0.0     0.9                       -1.0   

   current_address_months_count  customer_age  days_since_request  \
0                         305.0          60.0            0.030059   
2                         140.0          50.0            0.015659   
4                         171.0          50.0            0.001409   
5                          85.0          30.0            0.027292   
7                          39.0          30.0            0.010945   

   intended_balcon_amount payment_type  zip_count_4w  ...  month        x1  \
0               -1.599455           AC         990.0  ...    2.0 -0.245425   
2                3.951994           AA        1269.0  ...    7.0  0.009336   
4               28.159779           AB        4430.0  ...    1.0  2.229616   
5               -1.310498           AB        1698.0  ...    3.0 -0.193945   
7               -1.450972           AC         569.0  ...    3.0 -2.440650   

         x2  name_email_similarity date_of_birth_distinct_emails_4w  \
0  0.568811               0.883485                              2.0   
2 -2.096682               0.113208                              4.0   
4 -0.005823               0.792797                              4.0   
5  0.861207               0.865082                             10.0   
7  0.354986               0.450024                             13.0   

   email_is_free device_distinct_emails_8w  phone_home_valid  \
0            1.0                       1.0               0.0   
2            1.0                       1.0               1.0   
4            0.0                       1.0               0.0   
5            0.0                       1.0               0.0   
7            1.0                       1.0               0.0   

   phone_mobile_valid  segmentacion_etaria  
0                 1.0        Persona Mayor  
2                 1.0               Adulto  
4                 1.0               Adulto  
5                 1.0               Adulto  
7                 0.0               Adulto  

[5 rows x 36 columns]

## 3. Análisis Exploratorio de Datos

In [ ]:
!pip install ydata_profiling


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.3/352.3 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 kB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 19.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.4/455.4 kB 34.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 80.4 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=e2b6434c0622d316fdebac1514333556329ac5e3dbfdbc4bb8300226cbdd0c04
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
  Attempting uninstall: wordcloud
    Found existing installation: wordcloud 1.8.2.2
    

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="EDA")
profile.to_file("eda.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

### 3.1 Análisis del EDA

- Se puede notar primeramente que no existen valores nulos según la matriz de Missing values que se generó, esto es razonable ya que hicimos un tratamiento respecto a esto, sin embargo como veremos en este análisis, hay alguna variables que usan negativos para guardar missing values.
- Respecto a filas duplicadas, estas no existen, ya que hicimos tratamiento de esto.
- Se tienen 873771 y 36 variables con un espacio en memoria de 240.8 MiB

Respecto a las distribuciones de las variables se puede notar lo siguiente:

- Los IDs van de 0 a 999999 y no hay IDs repetidos ya que hay 873771 distinct values, ademas que la distribucion es uniforme en los reales

- La variable fraud_bool esta claramente desbalanceada hacia aplicaciones o registros no fraudulentos 98.9%  vs 1.1% fraudulentos. 

- La variable income es una variable que agrupa en deciles segun el nivel de sueldo de las personas, va desde el decil 0.1 a 0.9, ademas  se observa que el primer cuartil (Q1) es 0.3, la mediana es 0.6 y el tercer cuartil (Q3) es 0.8 Además se puede notar que el valor más frecuente es 0.9, seguido de 0.8 y 0.1, mientras que los valores menos frecuentes son 0.5, 0.3 y 0.2. 
Se puede notar que la variable income presenta una distribución desigual, se asemeja  a una distribución exponencial con una mayor concentración de valores en los deciles superiores (0.8 y 0.9), hay un claro desbalance de los datos, ya que se tienen personas con ingresos muy bajos que son el 14.5% del decil 0.1 y demasiadas personas con ingresos altos, ya que  39.2 % son del decil 8 y 9, esto indica que hay muchos solicitantes que tienen ingresos altos en comparación con los de ingresos medianamente bajos o intermedios.

- Para la variable prev_address_months_count se observa que la mayoría de los registros (76.2%) tienen un valor de -1, lo que indica que no se dispone de información sobre la dirección anterior. Esto sugiere un desequilibrio significativo en los datos, donde la gran mayoría de los solicitantes no tienen información registrada sobre su residencia anterior.
Se observa que el el rango es de 400 y el tercer cuartil (Q3) es -1. Además la asimetría (skewness) es bastante alta, con un valor de 4.321071, lo cual indica una cola larga en la distribución. Esta alta asimetría en conjunto con esta distribución hacia mayores valores con registros -1, puede ser un indicio de la presencia de outliers en los extremos de la distribución. En cuanto al tipo de distribución, esta se asemeja a una distribución logarítmica o 1/x con un alto desequilibrio de los datos.

- La variable current_address_months_count muestra una distribución asimétrica positiva, con una mayor concentración de valores en el extremo inferior. Con un rango intercuartil de 127 y una mediana de 64, la distribucion se asemeja a un logaritmo y es una distribucion decreciente, esto muestra que la mayoria de clientes lleva poco tiempo en su dirección actual, aunque segun las estadisticas descriptivas existen clientes que llevan mucho tiempo en su dirección actual que son basicamente outliers en el extremo superior de la distribución.

- La variable customer_age muestra una distribución relativamente simétrica parecida a una normal, con una concentración notable de valores alrededor de las décadas de 30, 40 y 50. El primer cuartil (Q1) se encuentra en 30 años, la mediana en 50 años y el tercer cuartil (Q3) en 50 años también. Esto indica que una gran proporción de solicitantes tiene edades comprendidas entre los 30 y 50 años. Además, se observa que la desviación estándar es de 13.76, lo que indica una dispersión moderada de las edades. La variable muestra una ligera asimetría negativa -0.20, lo que sugiere que hay una ligera tendencia hacia edades relativamente jóvenes menores a 50 años En cuanto a los valores atípicos, se encuentran pocos casos en las edades de 80 y 90 años, que representan menos del 1% de los clientes. En general, la distribución de la variable "customer_age" se caracteriza por una concentración en edades de adulto y adulto joven y una disminución gradual a medida que aumenta la edad.

- La variable days_since_request muestra una distribución altamente asimétrica positiva con un valor de 9.976, con una concentración notable de valores cercanos a cero. El primer cuartil (Q1) se encuentra en 0.007 días, la mediana en 0.016 días y el tercer cuartil (Q3) en 0.027 días, además la desviación estándar de 4.997 y el coeficiente de variación de 5.536 indican una dispersión significativa. Esto indica que la mayoría de las solicitudes se realizaron recientemente en días o incluso horas recientes. En cuanto a los posibles valores atípicos, hay unos cuantos valores que representan que representan menos del 0.1% de las solicitudes, esto indica que hay algunas solicitudes que se realizaron hace más de un 1 día y hay otras pocas que se realizan hace menos de 0.036 días también representando todas estas menos 1% de los datos.

- La variable intended_balcon_amount muestra una distribución asimétrica positiva con un valor de 2.585, con una concentración de valores en el extremo inferior. El primer cuartil (Q1) se encuentra en -1.180, la mediana en -0.835 y el tercer cuartil (Q3) en -0.066. Esto indica que la mayoría de los solicitantes tienen la intención de transferir montos relativamente pequeños. En cuanto a los posibles valores atípicos, hay personas con intención de transferir montos grandes o medianamente grandes en torno a 112 (menos del 1%) pero son muy pocas.

- Para la variable payment_type se puede notar que el valor "AB" aparece con mayor frecuencia, con un total de 348,705 casos, lo que representa el 39.9% de las observaciones. Le sigue el valor "AA" con 217,944 casos (24.9%) y luego el valor "AC" con 215,904 casos (24.7%). El valor "AD" tiene una frecuencia de 91,011 casos, lo que equivale al 10.4% de las observaciones. Finalmente, el valor "AE" tiene una frecuencia muy baja, con solo 207 casos, lo que representa menos del 0.1% de las observaciones. Esto implica un claro desbalance de clases  con una predominancia o preferencia por los tipos de pago AB, AA y AC, y con poca preferencia por los  AD y AE.

- Para zip_count_4w podemos observar que el rango de valores es bastante amplio, el valor mínimo registrado es 1, el percentil 5 es 492, el primer cuartil (Q1) es 886, la mediana es 1208, el tercer cuartil (Q3) es 1844 y el percentil 95 es 3544. El promedio de solicitudes por código postal es de aproximadamente 1518, lo que sugiere que, en general, hay un número considerable de solicitudes en cada área. Sin embargo, la dispersión de los datos es alta, como se refleja en la desviación estándar de 965. Esto significa que la cantidad de solicitudes puede variar significativamente de un código postal a otro. Hay algunos códigos postales con una mayor concentración de solicitudes, como los valores 1014 o 924. Estos códigos postales pueden ser áreas de mayor interés o demanda potencial a prestar atención. La distribución es un tanto variable pero es parecida a una normal centrada o con una mayor cantidad de datos en torno a la mediana y el quartil 3.

- La variable velocity_6h muestra la variabilidad en la velocidad de las solicitudes de crédito en un período de 6 horas. Los datos muestran que hay momentos de mayor velocidad de solicitudes y momentos de menor velocidad es mas el valor mínimo es -174.11 o disminución de solicitudes de crédito, se tiene además una mediana de 5190 con un rango intercuartil de 4033.95, la distribución es una normal clara con una desviación muy alta de 2940.4648 existen outliers debido a valores muy altos de 12500 para arriba, pero en general no hay presencia de valores extremadamente alejados de la media.

- Lo mismo sucede con velocity_24h y velocity_4w ambas tienen cierta simetría normal con promedios muy parecidos de 4660.4553 y 4734.2333 respectivamente, claramente hay outliers que son los momentos cuando hay demasiadas solicitudes o muy pero muy pocas.

- La variable bank_branch_count_8w presenta una distribución demasiado desigual concentrada en 0 y 31 con una mayor frecuencia de 0 y 1 sucursales, esto podría indicar áreas o momentos en los que no hay sucursales bancarias disponibles. La mediana esta en 10 sucursales, la desviación es muy alta de 473.42, con todo esto es claro que existen demasiados outliers con valores muy altos, esto podría deberse a que pocas veces hay muchas sucursales operativas en un periodo de 8 semanas, esta variable podría estar evidenciando que existe poca disponibilidad de sucursales y una alta variabilidad de las mismas, por lo que se debería prestar atención ya que podríamos estar desaprovechando la demanda de clientes o teniendo un problema logístico grave. 

- Con respecto a la variable employment_status claramente hay un desbalance en torno a la clase CA con un recuento de 598,651 personas o un 68.5% de los datos.

- Para la variable credit_risk_score se puede observar una normal muy marcada en torno a una media  de 139.2571 el IQR es de 98 y la desviacion estándar es relativamente alta de 71.432183, esto indica que existe cierta cantidad de outliers tanto en personas con un credit risk score muy bajo y personas con uno muy alto superior al 95 percentil que es 267. Existe igualmente score negativo lo cual indica que hay ciertas personas con un score muy pero muy malo.

- Respecto a la variable housing_status hay una clara tendencia a personas con casas con status BA, BB y BC siendo estas dos últimas la de mayor frecuencia 30.1% y 33.5% respectivamente.

- Se puede observar para
bank_months_count, que la mayoría de las cuentas bancarias tienen una duración relativamente corta, con una mediana de 6 meses y el 75% de las cuentas duran 25 meses o menos, además la distribución es bastante desigual pero en general con una gran cantidad de datos 95 percentil (menor a 30 meses). Sin embargo, es importante tener en cuenta que existen valores de meses negativos en los percentiles más bajos, ya que podrían indicar problemas al registrar los meses de duración de las cuentas o que el mes -1 por ejemplo signifique algo interno, como cuenta que aún no se ha abierto, etc.

- Según la variable has_other_cards que es un bool, existe un 75% (bool 0) y 25% (bool 1) de clientes que no tienen y que tienen otras tarjetas de débito o crédito respectivamente, esto presenta un claro desbalance y podría ser una oportunidad de mejora para ofrecer tarjetas o cuentas mas atractivas para que mas clientes tengan otras tarjetas.

- Según la variable foreign_request en general se han realizado pocas solicitudes relacionadas con el extranjero, con un 97.6% (bool 0) y 2.4% (bool 1).

- Según la variable source, la mayoría de solicitudes de aplicación se hicieron vía internet 99.2% seguido de teleapp con un 0.8%, este desbalance si bien es demasiado alto es propio de este tipo de servicios, además de que en general por seguridad en estos tiempos las personas estan prefiriendo canales online.

- Según la variable session_length_in_minutes se puede observar un claro logaritmo, concentrandose la duración de la sesion en pocas minutos la media es 7.81 minutos y el percentil 95 es de 22.53 minutos, con un IQR de 6.2 y una desviacion de 8.24 aprox, lo que sugiere que en general las personas duran poco tiempo en la sesión, existen valores atípicos a considerar por ejemplo minutos con valor -1 en el 0.2% de las muestras esto podría ser un error o algún estándar de inputacion para esta variable por parte del banco, también existen según el histograma outliers mayores a 23 minutos, esto podría deberse a personas que dejan abierto la sesion mientras hacen otras cosas, también hay outliers de personas que se demoran segundos en la sesión lo que podría deberse a personas que simplemente se arrepintieron de hacer la solicitud o salieron de improviso.

- Con respecto a la variable device_os un porcentaje considerable de los dispositivos utilizan el sistema operativo Linux 33.7%, windows 30.4%, Macintosh 5%, x11 que es comúnmente asociado con sistemas Unix y Linux (0.8%). Notemos que si bien hay un pequeño desbalance de clases en general, los OS de los dispositivos son uniformes, además notemos que Android esta hecho a base de linux y otros podría deberse a sistemas IOS de Iphone por lo que tiene sentido este desbalance.

- La variable keep_alive_session indica que la mayoría de las interacciones o transacciones se mantuvo una sesión activa 55.6% un 44.4% de las veces no. En general esta muy balanceado esto sin embargo como banco queremos un mayor numer de transacciones con un alive session ya que asi tendriamos mas probilidades de que el cliente realize una transaccion o solicitud. 

- Para la variable device_fraud_count no se detectaron aplicaciones fraudulentas basadas en el dispositivo utilizado en el conjunto de datos analizado. Claramente hay un desbalance, sin embargo esto podría ser bueno ya que un porcentaje del 100% de aplicaciones no fraudulentas en relación al dispositivo implica que las medidas de seguridad del banco en general son buenas.

- La variable month es simetrica con una normal, no se visualizan posibles outliers, ya que existe una distribución relativamente equilibrada de solicitudes a lo largo de los meses (sesgo es cercano a cero -0.057323507), con una mayor concentración en los meses 2, 3, 4 y 5.

- Para la variable x1 se tiene una distribución normal muy marcada que se extiende desde valores negativos (-4.97) hasta valores positivos, con una concentración en el rango intercuartil y una mediana de 0.0067. Los datos muestran una dispersión moderada y una ligera e imperceptible asimetría hacia la derecha (Skewness	0.065)

- Para la variable x2 se tiene una distribución normal muy marcada que se extiende desde valores negativos (-4.84) hasta valores positivos, la distribución de la variable muestra una concentración en el rango intercuartil (Q1 a Q3) alrededor de la mediana. La desviación estándar es 1.0124485, lo que indica una dispersión moderada de los datos alrededor de la media.

- Para la variable name_email_similarity revela una distribución de la variable que no se asemeja a una distribución normal. El sesgo (skewness) es ligeramente positivo (0.0704), lo que indica una ligera asimetría hacia la derecha. Además, la curtosis es de de -1.308 sugiere una distribución relativamente plana con colas más ligeras que una distribución normal. Además la variable muestra una concentración de valores alrededor de la mediana, que es 0.4860. Esto indica que la mayoría de las solicitudes tienen una similitud moderada entre el nombre y el correo electrónico del solicitante. En resúmen según se puede observar en general las personas tratan de tener un correo lo más parecido a su nombre, sin embargo por motivos ajenos a este estudio, existen igualmente personas que tienen una baja similitud entre nombre y correo a lo hora de hacer su solicitud.

- Según la variable "date_of_birth_distinct_emails_4w", se puede observar una distribución que se concentra en un rango de valores de pocos correos distintos. La media de esta variable es de 7.77, y el percentil 95 es de 17. Esto indica que la mayoría de las muestras se encuentran en un rango relativamente estrecho.
El rango intercuartílico (IQR) es de 7, lo que indica que la dispersión de los datos dentro del rango intercuartílico es moderada. La desviación estándar es de aproximadamente 4.82, lo que sugiere una variabilidad considerable en los datos.
Se observa una frecuencia significativa de valores como 6, 5, 4, y 7, lo que indica una concentración de muestras en esos valores específicos. Además, hay outliers en el extremo superior del rango, con valores mayores a 23, estos outliers representan casos inusuales en los que las personas tienen una cantidad alta de correos electrónicos distintos asociados a su fecha de nacimiento en un período de 4 semanas.

- Para la variable "email_is_free" existen dos clases el valor 1.0, que indica que el correo electrónico es gratuito y el valor 0.0, que indica que el correo electrónico no es gratuito. Según se puede observar la mayoría de las muestras tienen correos electrónicos gratuitos, mientras que una proporción ligeramente menor tiene correos electrónicos que no son gratuitos.

- La variable "device_distinct_emails_8w" muestra una predominancia abrumadora del valor 1.0 (96.4%), lo que indica que la mayoría de las personas utilizan un único dispositivo para acceder a los correos electrónicos en un período de 8 semanas. Sin embargo, también existen casos en los que se utilizan dos dispositivos distintos o ninguno. La presencia de valores atípicos como -1.0 (0.1%) indica la necesidad de considerar posibles errores de inputación para estas muestras. Algo que nos llamo la atencion es que hay muestras con valor 0.0 lo que indica que hubieron personas que no accedieron en un periodo de 8 semanas seguidas mediante su dispositivo.

- La variable "phone_home_valid" muestra una distribución equilibrada entre los valores 0.0 y 1.0, lo que indica que hay una proporción similar de personas con números de teléfono de casa válidos (50.7%) y 49.3% no válidos en las muestras.

- La variable "phone_mobile_valid" muestra que la mayoría de las personas tienen un número de teléfono móvil válido registrado (85.7%), aunque existe una proporción significativa de personas que no tienen un número válido o no proporcionaron información sobre su número de teléfono móvil (14.3%).

- La variable segmentacion_etaria la creamos a partir de customer_age (numeric) y como se puede apreciar en la distribución y tal cual lo dijimos para la variable customer_age (numeric) las solicitudes estan concentradas en personas Adultas y Adultas jóvenes, aunque existen personas jóvenes (menores a 18 años) y personas mayores que representan el 12.2% (Mayor a 60 años)


En resumen, existen 5 variables que nos llaman mucho la atención: 

- "income": Esta variable muestra una concentración de valores en los deciles superiores, lo que indica un desbalance en los ingresos de los solicitantes, con una gran cantidad de registros de ingresos altos en comparación con los ingresos bajos o intermedios.

- "prev_address_months_count" y "current_address_months_count": Ambas variables tienen una fuerte concentracion en el valor -1, lo cual sugiere una falta de información sobre las direcciones anteriores y actuales de los solicitantes. Esto podría ser un indicio de datos faltantes que se debería corregir.

- "fraud_bool": Esta variable muestra un gran desbalance de clases, con el 98.9% de los registros correspondiendo a aplicaciones no fraudulentas y solo el 1.1% siendo fraudulentas. Este desequilibrio puede afectar el rendimiento de los modelos de detección de fraudes y requerir técnicas de muestreo o ajuste.

- "payment_type": Esta variable presenta un desbalance de clases, con algunos tipos de pago siendo mucho más frecuentes que otros. Esto puede influir en el análisis de patrones de comportamiento de pago.

- "days_since_request": Esta variable muestra una concentración de valores cercanos a cero, lo que indica que la mayoría de las solicitudes se realizaron recientemente. Esta información puede ser útil para comprender la frecuencia de solicitudes y puede ser relevante para la gestión de solicitudes.




Con respecto a las correlaciones, usando el Heatmap del EDA se puede observar ciertas correlaciones muy interesantes.

- Algunas variables  están altamente correlacionadas entre sí, lo cual puede indicar una fuerte relación o dependencia entre ellas. Por ejemplo, "velocity_6h", "velocity_24h" y "velocity_4w" están altamente correlacionadas entre sí, lo que sugiere que están midiendo conceptos similares.

- La variable customer_age claramente tiene y esta altamente correlacionada con segmentacion_etaria

-  La variable "income" tiene una correlación positiva moderada con las variables "intended_balcon_amount" (0.108) esto indica que a medida que el ingreso de los clientes aumenta, tienden a solicitar montos más altos para préstamos o créditos y  también entre income y "credit_risk_score" (0.186), esto indica que los clientes con ingresos más altos tienden a tener una mejor puntuación de riesgo crediticio.

- La variable "prev_address_months_count" muestra una correlación negativa fuerte con la variable "current_address_months_count" (-0.611), lo que indica que hay una tendencia a que los clientes se muden con menos frecuencia.

- La variable "customer_age" tiene una correlación positiva moderada con las variables "days_since_request" (0.039) y "session_length_in_minutes" (0.054), lo que sugiere que los clientes más jóvenes tienden a solicitar servicios con mayor frecuencia y tener sesiones más largas.

- La variable "velocity_6h" está fuertemente correlacionada con la variable "velocity_24h" (0.457) y la variable "velocity_4w" (0.384), lo que indica una relación positiva entre la velocidad de transacciones en diferentes períodos de tiempo.

- La variable "credit_risk_score" muestra una correlación positiva moderada con la variable "bank_months_count" (0.501), lo que sugiere que los clientes con mayor antigüedad en el banco tienen una mejor puntuación de riesgo crediticio.

- La variable "proposed_credit_limit" tiene una correlación positiva moderada con la variable "credit_risk_score" (0.661), lo que indica que los clientes con una mejor puntuación de riesgo crediticio tienden a tener límites de crédito más altos propuestos.

- La variable "month" muestra una correlación negativa moderada con la variable "velocity_4w" (-0.837), lo que sugiere una disminución en la velocidad de transacciones a lo largo del tiempo.


- La variable "name_email_similarity" muestra una correlación positiva moderada con la variable "credit_risk_score" (0.060), lo que sugiere que los clientes con una mayor similitud entre su nombre y dirección de correo electrónico tienden a tener una mejor puntuación de riesgo crediticio.

- La variable "income" tiene una correlación negativa moderada con la variable "zip_count_4w" (-0.079), lo que indica que los clientes con ingresos más altos tienden a tener menos códigos postales únicos asociados en un período de 4 semanas.

- La variable "prev_address_months_count" muestra una correlación positiva moderada con la variable "zip_count_4w" (0.128), lo que sugiere que los clientes que han vivido en una dirección por más tiempo tienden a tener más códigos postales únicos asociados en un período de 4 semanas.

- La variable "current_address_months_count" tiene una correlación positiva moderada con la variable "zip_count_4w" (0.198), lo que indica que los clientes que han vivido en su dirección actual por más tiempo tienden a tener más códigos postales únicos asociados en un período de 4 semanas.

- La variable "income" muestra una correlación positiva moderada con la variable "session_length_in_minutes" (0.087), lo que sugiere que los clientes con ingresos más altos tienden a tener sesiones más largas.

- La variable "name_email_similarity" tiene una correlación positiva moderada con la variable "session_length_in_minutes" (0.074), lo que indica que los clientes con una mayor similitud entre su nombre y dirección de correo electrónico tienden a tener sesiones más largas.

- La variable "credit_risk_score" muestra una correlación positiva moderada con la variable "intended_balcon_amount" (0.135), lo que sugiere que los clientes con una mejor puntuación de riesgo crediticio tienden a solicitar montos más altos para préstamos o créditos.

## 4. Preprocesamiento

In [ ]:
# Antes recordemos un poco como era el df
df.head(5)


id  fraud_bool  income  prev_address_months_count  \
0  729517         0.0     0.7                       -1.0   
2  149585         0.0     0.8                       -1.0   
4   64486         0.0     0.9                       -1.0   
5  825283         0.0     0.5                       -1.0   
7    8308         0.0     0.9                       -1.0   

   current_address_months_count  customer_age  days_since_request  \
0                         305.0          60.0            0.030059   
2                         140.0          50.0            0.015659   
4                         171.0          50.0            0.001409   
5                          85.0          30.0            0.027292   
7                          39.0          30.0            0.010945   

   intended_balcon_amount payment_type  zip_count_4w  ...  month        x1  \
0               -1.599455           AC         990.0  ...    2.0 -0.245425   
2                3.951994           AA        1269.0  ...    7.0  0.009336   
4               28.159779           AB        4430.0  ...    1.0  2.229616   
5               -1.310498           AB        1698.0  ...    3.0 -0.193945   
7               -1.450972           AC         569.0  ...    3.0 -2.440650   

         x2  name_email_similarity date_of_birth_distinct_emails_4w  \
0  0.568811               0.883485                              2.0   
2 -2.096682               0.113208                              4.0   
4 -0.005823               0.792797                              4.0   
5  0.861207               0.865082                             10.0   
7  0.354986               0.450024                             13.0   

   email_is_free device_distinct_emails_8w  phone_home_valid  \
0            1.0                       1.0               0.0   
2            1.0                       1.0               1.0   
4            0.0                       1.0               0.0   
5            0.0                       1.0               0.0   
7            1.0                       1.0               0.0   

   phone_mobile_valid  segmentacion_etaria  
0                 1.0        Persona Mayor  
2                 1.0               Adulto  
4                 1.0               Adulto  
5                 1.0               Adulto  
7                 0.0               Adulto  

[5 rows x 36 columns]

In [ ]:
df.describe

<bound method NDFrame.describe of              id  fraud_bool  income  prev_address_months_count  \
0        729517         0.0     0.7                       -1.0   
2        149585         0.0     0.8                       -1.0   
4         64486         0.0     0.9                       -1.0   
5        825283         0.0     0.5                       -1.0   
7          8308         0.0     0.9                       -1.0   
...         ...         ...     ...                        ...   
1137187  707063         0.0     0.1                       -1.0   
1137188  784606         0.0     0.5                       -1.0   
1137189  216375         0.0     0.8                       46.0   
1137190   41856         0.0     0.7                       25.0   
1137191  988191         0.0     0.9                       -1.0   

         current_address_months_count  customer_age  days_since_request  \
0                               305.0          60.0            0.030059   
2                      

In [ ]:
num_unique_values = df.nunique()
num_unique_values

id                                  873771
fraud_bool                               2
income                                   9
prev_address_months_count              373
current_address_months_count           416
customer_age                             9
days_since_request                  865279
intended_balcon_amount              869846
payment_type                             5
zip_count_4w                          6222
velocity_6h                         872758
velocity_24h                        873005
velocity_4w                         872391
bank_branch_count_8w                  2317
employment_status                        7
credit_risk_score                      543
housing_status                           7
bank_months_count                       33
has_other_cards                          2
proposed_credit_limit                   12
foreign_request                          2
source                                   2
session_length_in_minutes           869648
device_os  

### 4.1 Declarar `ColumnTransformer`

### 4. Preparación de Datos [1 Punto]

*Esta sección consiste en generar los distintos pasos para preparar sus datos con el fin de luego poder crear su modelo.*

Dentro de los aspectos minimos que se les solicitarán en este desarrollo estan:

- Definir preprocesadores para datos categóricos y ordinales.
- Setear las transformaciones en un `ColumnTransformer`.
- Transformar todo el datset.

**Notas**: 

- Las variables `id` y `fraud_bool` no deben ser transformadas, pero si pasadas a la siguiente etapa. (Estudiar la transformación `passthrough`).
- La salida de la transformación debe ser un pandas dataframe. Para esto, investiguen acerca de la nueva [`set_output` API](https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html). Si se levanta un error por matriz sparse, desactiven su uso en la transformación correspondiente.

In [ ]:

# Antes de seguir, clasifiquemos en las siguiente lista las variables ordinales y categoricas:

ordinal_features = ['income', 'credit_risk_score']
categorical_features = [
                        'payment_type', 'employment_status', 'housing_status', 'source', 'device_os',
                        'segmentacion_etaria','has_other_cards', 'foreign_request', 'email_is_free',
                        'phone_home_valid', 'phone_mobile_valid', 'keep_alive_session'
                        ]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

''' 
from sklearn.compose import ColumnTransformer y from sklearn.preprocessing import StandardScaler, OneHotEncoder 
se utilizan para definir y aplicar transformaciones específicas a diferentes conjuntos de características en un pipeline 
de preprocesamiento. ColumnTransformer permite aplicar transformaciones de manera selectiva a columnas específicas, 
mientras que StandardScaler y OneHotEncoder son preprocesadores comunes utilizados para estandarizar variables numéricas y
codificar variables categóricas, respectivamente.

'''

# Defininiendo preprocesadores para datos categóricos y ordinales 

categorical_transformer = OneHotEncoder(handle_unknown='ignore', sparse=False)
ordinal_transformer = StandardScaler()

# Seteando las transformaciones en un ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
        ('ord', ordinal_transformer, ordinal_features),
        ('passthrough', 'passthrough', ['id', 'fraud_bool'])
    ])


### 4.2 Transformar datos

In [ ]:
from sklearn import set_config

''' 
from sklearn import set_config nos permite configurar opciones globales en scikit-learn. 
En este caso, usamos set_config(transform_output="pandas") para obtener la salida de la transformación 
como un DataFrame de pandas directamente. Esto evita la necesidad de convertir manualmente los datos transformados en un DataFrame.
'''

# Transformando el dataset df y seteando la salida como un dataframe
set_config(transform_output="pandas")
preprocessed_data = preprocessor.fit_transform(df)

# Convertir el resultado en un DataFrame
preprocessed_df = pd.DataFrame(preprocessed_data)

#Llamando a la bd final db, ya que usamos mucho df 
db = preprocessed_df
db.head(10)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


cat__payment_type_AA  cat__payment_type_AB  cat__payment_type_AC  \
0                    0.0                   0.0                   1.0   
2                    1.0                   0.0                   0.0   
4                    0.0                   1.0                   0.0   
5                    0.0                   1.0                   0.0   
7                    0.0                   0.0                   1.0   
9                    1.0                   0.0                   0.0   
11                   1.0                   0.0                   0.0   
12                   0.0                   1.0                   0.0   
13                   0.0                   1.0                   0.0   
15                   0.0                   1.0                   0.0   

    cat__payment_type_AD  cat__payment_type_AE  cat__employment_status_CA  \
0                    0.0                   0.0                        0.0   
2                    0.0                   0.0                        0.0   
4                    0.0                   0.0                        0.0   
5                    0.0                   0.0                        1.0   
7                    0.0                   0.0                        1.0   
9                    0.0                   0.0                        0.0   
11                   0.0                   0.0                        1.0   
12                   0.0                   0.0                        0.0   
13                   0.0                   0.0                        0.0   
15                   0.0                   0.0                        1.0   

    cat__employment_status_CB  cat__employment_status_CC  \
0                         0.0                        1.0   
2                         0.0                        0.0   
4                         0.0                        1.0   
5                         0.0                        0.0   
7                         0.0                        0.0   
9                         0.0                        1.0   
11                        0.0                        0.0   
12                        1.0                        0.0   
13                        1.0                        0.0   
15                        0.0                        0.0   

    cat__employment_status_CD  cat__employment_status_CE  ...  \
0                         0.0                        0.0  ...   
2                         0.0                        0.0  ...   
4                         0.0                        0.0  ...   
5                         0.0                        0.0  ...   
7                         0.0                        0.0  ...   
9                         0.0                        0.0  ...   
11                        0.0                        0.0  ...   
12                        0.0                        0.0  ...   
13                        0.0                        0.0  ...   
15                        0.0                        0.0  ...   

    cat__phone_home_valid_0.0  cat__phone_home_valid_1.0  \
0                         1.0                        0.0   
2                         0.0                        1.0   
4                         1.0                        0.0   
5                         1.0                        0.0   
7                         1.0                        0.0   
9                         0.0                        1.0   
11                        0.0                        1.0   
12                        0.0                        1.0   
13                        1.0                        0.0   
15                        1.0                        0.0   

    cat__phone_mobile_valid_0.0  cat__phone_mobile_valid_1.0  \
0                           0.0                          1.0   
2                           0.0                          1.0   
4                           0.0                          1.0   
5                           0.0                          1.0   
7    

In [ ]:
df

id  fraud_bool  income  prev_address_months_count  \
0        729517         0.0     0.7                       -1.0   
2        149585         0.0     0.8                       -1.0   
4         64486         0.0     0.9                       -1.0   
5        825283         0.0     0.5                       -1.0   
7          8308         0.0     0.9                       -1.0   
...         ...         ...     ...                        ...   
1137187  707063         0.0     0.1                       -1.0   
1137188  784606         0.0     0.5                       -1.0   
1137189  216375         0.0     0.8                       46.0   
1137190   41856         0.0     0.7                       25.0   
1137191  988191         0.0     0.9                       -1.0   

         current_address_months_count  customer_age  days_since_request  \
0                               305.0          60.0            0.030059   
2                               140.0          50.0            0.015659   
4                               171.0          50.0            0.001409   
5                                85.0          30.0            0.027292   
7                                39.0          30.0            0.010945   
...                               ...           ...                 ...   
1137187                         260.0          60.0            0.026023   
1137188                          30.0          50.0            0.052916   
1137189                           0.0          30.0            0.005857   
1137190                          18.0          30.0            1.426644   
1137191                          56.0          30.0            0.006165   

         intended_balcon_amount payment_type  zip_count_4w  ...  month  \
0                     -1.599455           AC         990.0  ...    2.0   
2                      3.951994           AA        1269.0  ...    7.0   
4                     28.159779           AB        4430.0  ...    1.0   
5                     -1.310498           AB        1698.0  ...    3.0   
7                     -1.450972           AC         569.0  ...    3.0   
...                         ...          ...           ...  ...    ...   
1137187               -0.587295           AB        1795.0  ...    5.0   
1137188               -1.249585           AB        1039.0  ...    1.0   
1137189               -0.380745           AB         918.0  ...    3.0   
1137190               10.441915           AA        1188.0  ...    3.0   
1137191               -1.103130           AD        1922.0  ...    4.0   

               x1        x2  name_email_similarity  \
0       -0.245425  0.568811               0.883485   
2        0.009336 -2.096682               0.113208   
4        2.229616 -0.005823               0.792797   
5       -0.193945  0.861207               0.865082   
7       -2.440650  0.354986               0.450024   
...           ...       ...                    ...   
1137187  0.397897 -0.103541               0.870118   
1137188  1.713050 -1.911669               0.094715   
1137189 -0.727536 -1.540993               0.437026   
1137190  1.642429 -0.026783               0.449010   
1137191 -1.662247  1.576214               0.769959   

        date_of_birth_distinct_emails_4w  email_is_free  \
0                                    2.0            1.0   
2                                    4.0            1.0   
4                                    4.0            0.0   
5                                   10.0            0.0   
7                                   13.0            1.0   
...                                  ...            ...   
1137187                              3.0            1.0   
1137188                              5.0            0.0   
1137189                             13.0            0.0   
1137190                             15.0            0.0   
1137191                             10.0            1.0   

        device_distinct_emails_8w  phone_home_valid  phone_mobile_valid 

In [ ]:
db.to_csv('process_data.csv', index=False)

In [ ]:
db.columns

Index(['cat__payment_type_AA', 'cat__payment_type_AB', 'cat__payment_type_AC',
       'cat__payment_type_AD', 'cat__payment_type_AE',
       'cat__employment_status_CA', 'cat__employment_status_CB',
       'cat__employment_status_CC', 'cat__employment_status_CD',
       'cat__employment_status_CE', 'cat__employment_status_CF',
       'cat__employment_status_CG', 'cat__housing_status_BA',
       'cat__housing_status_BB', 'cat__housing_status_BC',
       'cat__housing_status_BD', 'cat__housing_status_BE',
       'cat__housing_status_BF', 'cat__housing_status_BG',
       'cat__source_INTERNET', 'cat__source_TELEAPP', 'cat__device_os_linux',
       'cat__device_os_macintosh', 'cat__device_os_other',
       'cat__device_os_windows', 'cat__device_os_x11',
       'cat__segmentacion_etaria_Adulto',
       'cat__segmentacion_etaria_Adulto-Joven',
       'cat__segmentacion_etaria_Joven',
       'cat__segmentacion_etaria_Persona Mayor', 'cat__has_other_cards_0.0',
       'cat__has_other_cards_1.0

## 5. Visualización en Baja Dimensionalidad

### 5.1 Muestrear dataframe

In [ ]:
from sklearn.decomposition import PCA
import plotly.express as px

datos_muestreo = 15000
df_sample = db.sample(datos_muestreo, random_state = 24)
df_sample

cat__payment_type_AA  cat__payment_type_AB  cat__payment_type_AC  \
1079999                   0.0                   0.0                   0.0   
423176                    0.0                   1.0                   0.0   
118048                    1.0                   0.0                   0.0   
102686                    0.0                   1.0                   0.0   
64024                     1.0                   0.0                   0.0   
...                       ...                   ...                   ...   
213418                    0.0                   0.0                   1.0   
614416                    1.0                   0.0                   0.0   
593369                    0.0                   0.0                   0.0   
298926                    0.0                   1.0                   0.0   
249405                    0.0                   0.0                   1.0   

         cat__payment_type_AD  cat__payment_type_AE  \
1079999                   1.0                   0.0   
423176                    0.0                   0.0   
118048                    0.0                   0.0   
102686                    0.0                   0.0   
64024                     0.0                   0.0   
...                       ...                   ...   
213418                    0.0                   0.0   
614416                    0.0                   0.0   
593369                    1.0                   0.0   
298926                    0.0                   0.0   
249405                    0.0                   0.0   

         cat__employment_status_CA  cat__employment_status_CB  \
1079999                        0.0                        1.0   
423176                         0.0                        0.0   
118048                         1.0                        0.0   
102686                         0.0                        0.0   
64024                          1.0                        0.0   
...                            ...                        ...   
213418                         1.0                        0.0   
614416                         1.0                        0.0   
593369                         1.0                        0.0   
298926                         1.0                        0.0   
249405                         0.0                        0.0   

         cat__employment_status_CC  cat__employment_status_CD  \
1079999                        0.0                        0.0   
423176                         1.0                        0.0   
118048                         0.0                        0.0   
102686                         1.0                        0.0   
64024                          0.0                        0.0   
...                            ...                        ...   
213418                         0.0                        0.0   
614416                         0.0                        0.0   
593369                         0.0                        0.0   
298926                         0.0                        0.0   
249405                         0.0                        0.0   

         cat__employment_status_CE  ...  cat__phone_home_valid_0.0  \
1079999                        0.0  ...                        1.0   
423176                         0.0  ...                        0.0   
118048                         0.0  ...                        1.0   
102686                         0.0  ...                        0.0   
64024                          0.0  ...                        1.0   
...                            ...  ...                        ...   
213418                         0.0  ...                        0.0   
614416                         0.0  ...                        1.0   
593369                         0.0  ...                        0.0   
298926                         0.0  ...                        1.0   
249405                         0.0  ...                        0.0   

         cat__phone_

### 5.2 Proyectar y agregar proyecciones al dataframe de muestreo

In [ ]:
features = df_sample.drop(['passthrough__fraud_bool'], axis=1)
labels = df_sample['passthrough__fraud_bool']

# Realizar la proyección en baja dimensionalidad utilizando PCA
pca = PCA(n_components=2)
pca_result = pca.fit_transform(features)

# Agregar los resultados de la proyección al DataFrame
df_sample['pca_1'] = pca_result[:, 0]
df_sample['pca_2'] = pca_result[:, 1]

In [ ]:
df_sample['passthrough__fraud_bool'].unique()

array([0., 1.])

### 5.3 Visualizar según rangos etarios

In [ ]:
# Filtrar el dataframe para cada segmento y crear los gráficos de dispersión
segmentos = ['cat__segmentacion_etaria_Adulto', 'cat__segmentacion_etaria_Adulto-Joven', 'cat__segmentacion_etaria_Joven', 'cat__segmentacion_etaria_Persona Mayor']

for segmento in segmentos:
    df_segmento = df_sample[df_sample[segmento] == 1]  # Filtrar por el segmento actual
    
    fig = px.scatter(df_segmento, x='pca_1', y='pca_2', color='passthrough__fraud_bool', 
                     color_continuous_scale=['blue', 'red'], labels={'passthrough__fraud_bool': 'Fraude'})
    
    fig.update_traces(marker=dict(size=6))
    fig.update_layout(title=segmento)
    
    fig.show()

## 6. Anomalías

In [ ]:
15000/len(db.index)*100

1.7166969377560026

### 6.1 Implementar detector de anomalías sobre dataframe de muestreo

In [ ]:
import numpy as np

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    db.drop('passthrough__fraud_bool', axis=1),
    db['passthrough__fraud_bool'],
    test_size=0.3,
    random_state=42,
    stratify=db['passthrough__fraud_bool']
)

num_ones = int(y_train.sum())
num_ones_test = int(y_test.sum())

# Filtrar X_train para mantener solo las filas correspondientes a los valores 1 en y_test
X_train_filtered = X_train[y_train == 1]
X_test_filtered = X_test[y_test == 1]

# Calcular el número de filas a rellenar con valores 0 en X_train
num_zeros = 25000 - num_ones
num_zeros_test = 10000 - num_ones_test


# Obtener una muestra aleatoria sin reemplazo de filas con valores 0 de X_train
X_train_zeros = X_train[y_train == 0].sample(num_zeros, random_state=42)
X_test_zeros = X_test[y_test == 0].sample(num_zeros_test, random_state=42)

# Concatenar las filas con valores 1 y las filas con valores 0 para obtener el nuevo X_train
X_train_new = np.concatenate([X_train_filtered, X_train_zeros])
X_train_new = pd.DataFrame(X_train_new, columns = X_train.columns)
X_test_new = np.concatenate([X_test_filtered, X_test_zeros])
X_test_new = pd.DataFrame(X_test_new, columns = X_test.columns)

# Crear el nuevo y_train correspondiente a X_train_new
y_train_new = np.concatenate([np.ones(num_ones), np.zeros(num_zeros)])
y_train_new = pd.DataFrame(y_train_new)
y_test_new = np.concatenate([np.ones(num_ones_test), np.zeros(num_zeros_test)])
y_test_new = pd.DataFrame(y_test_new)


# Contar los valores de 1 y 0 en y_train y y_test
train_counts = y_train_new.value_counts()
test_counts = y_test_new.value_counts()

print("Valores de y_train:")
print(train_counts)
print()
print("Valores de y_test:")
print(test_counts)

Valores de y_train:
0.0    18265
1.0     6735
dtype: int64

Valores de y_test:
0.0    7113
1.0    2887
dtype: int64


In [ ]:
# Crear y entrenar el modelo XGBoost
model = xgb.XGBClassifier()
model.fit(X_train_new, y_train_new)

# Realizar predicciones en los datos de prueba
y_pred = model.predict(X_test_new)

In [ ]:
pd.DataFrame(y_pred).value_counts()

0    7743
1    2257
dtype: int64

### 6.2 Agregar resultados a dataframe de muestreo

In [ ]:
df_sample = X_test_new
df_sample.loc[:,'y_original'] = y_test_new
df_sample.loc[:,'y_pred'] = y_pred

In [ ]:
df_sample

cat__payment_type_AA  cat__payment_type_AB  cat__payment_type_AC  \
0                      0.0                   0.0                   1.0   
1                      0.0                   0.0                   1.0   
2                      0.0                   1.0                   0.0   
3                      0.0                   0.0                   0.0   
4                      0.0                   1.0                   0.0   
...                    ...                   ...                   ...   
9995                   0.0                   1.0                   0.0   
9996                   0.0                   1.0                   0.0   
9997                   0.0                   1.0                   0.0   
9998                   0.0                   0.0                   1.0   
9999                   1.0                   0.0                   0.0   

      cat__payment_type_AD  cat__payment_type_AE  cat__employment_status_CA  \
0                      0.0                   0.0                        1.0   
1                      0.0                   0.0                        1.0   
2                      0.0                   0.0                        1.0   
3                      1.0                   0.0                        0.0   
4                      0.0                   0.0                        1.0   
...                    ...                   ...                        ...   
9995                   0.0                   0.0                        1.0   
9996                   0.0                   0.0                        1.0   
9997                   0.0                   0.0                        1.0   
9998                   0.0                   0.0                        1.0   
9999                   0.0                   0.0                        0.0   

      cat__employment_status_CB  cat__employment_status_CC  \
0                           0.0                        0.0   
1                           0.0                        0.0   
2                           0.0                        0.0   
3                           1.0                        0.0   
4                           0.0                        0.0   
...                         ...                        ...   
9995                        0.0                        0.0   
9996                        0.0                        0.0   
9997                        0.0                        0.0   
9998                        0.0                        0.0   
9999                        1.0                        0.0   

      cat__employment_status_CD  cat__employment_status_CE  ...  \
0                           0.0                        0.0  ...   
1                           0.0                        0.0  ...   
2                           0.0                        0.0  ...   
3                           0.0                        0.0  ...   
4                           0.0                        0.0  ...   
...                         ...                        ...  ...   
9995                        0.0                        0.0  ...   
9996                        0.0                        0.0  ...   
9997                        0.0                        0.0  ...   
9998                        0.0                        0.0  ...   
9999                        0.0                        0.0  ...   

      cat__phone_home_valid_1.0  cat__phone_mobile_valid_0.0  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           0.0                          0.0   
3                           1.0                          0.0   
4                           0.0                          0.0   
...                         ...                          ...   
9995                        0.0                          0.0   
9996                        0.0                          0.0   
9997                        1.0           

### 6.3 Visualizar según rangos etarios

In [ ]:
features = df_sample.drop(['y_pred'], axis=1)
labels = df_sample['y_pred']

# Realizar la proyección en baja dimensionalidad utilizando PCA
pca = PCA(n_components=2)
pca_result = pca.fit_transform(features)

# Agregar los resultados de la proyección al DataFrame
df_sample.loc[:,'pca_1'] = pca_result.iloc[:, 0]
df_sample.loc[:,'pca_2'] = pca_result.iloc[:, 1]

# Filtrar el dataframe para cada segmento y crear los gráficos de dispersión
segmentos = ['cat__segmentacion_etaria_Adulto', 'cat__segmentacion_etaria_Adulto-Joven', 'cat__segmentacion_etaria_Joven', 'cat__segmentacion_etaria_Persona Mayor']

for segmento in segmentos:
    df_segmento = df_sample[df_sample[segmento] == 1]  # Filtrar por el segmento actual
    
    fig = px.scatter(df_segmento, x='pca_1', y='pca_2', color='y_pred', 
                     color_continuous_scale=['blue', 'red'], labels={'y_pred': 'Fraude'})
    
    fig.update_traces(marker=dict(size=6))
    fig.update_layout(title=segmento)
    
    fig.show()

### 6.4 Calcular ratios y responder

In [ ]:
datos_predichos_fraude = np.sum(df_sample.loc[:,'y_pred'])  # Cantidad total de datos predichos como fraude
datos_reales_fraude = np.sum(df_sample.loc[:,'y_original'])  # Cantidad total de ejemplos que eran realmente fraude
ejemplos_correctos_fraude = np.sum(np.logical_and(df_sample.loc[:,'y_pred'] == 1, df_sample.loc[:,'y_original'] == 1))  # Cantidad de ejemplos predichos correctamente como fraude

# Calcular los ratios P y R
P = ejemplos_correctos_fraude / datos_predichos_fraude
R = ejemplos_correctos_fraude / datos_reales_fraude

# Imprimir los resultados
print("Ratio P (Precisión):", P)
print("Ratio R (Recall):", R)

Ratio P (Precisión): 0.692512184315463
Ratio R (Recall): 0.5413924489089019
